version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # Porta AMQP
      - "15672:15672" # Porta de gerenciamento web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  api_principal:
    build: ./api_principal
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    entrypoint: [ "wait-for-it", "rabbitmq:5672", "--", "python", "app.py" ]
    networks:
      - app_network

  servico_notificacao:
    build: ./servico_notificacao
    depends_on:
      - rabbitmq
    entrypoint: [ "wait-for-it", "rabbitmq:5672", "--", "python", "worker.py" ]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
